// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-VFd2Ud7TThcne-ThlikQbCPYuDmNVM',
    appId: '1:307992644408:web:bd3bdd4b7ea1da79384fcd',
    messagingSenderId: '307992644408',
    projectId: 'wett-profis',
    authDomain: 'wett-profis.firebaseapp.com',
    databaseURL: 'https://wett-profis.firebaseio.com',
    storageBucket: 'wett-profis.firebasestorage.app',
    measurementId: 'G-4B9786P8J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuWaBFHR2YooUqAUFLVYusTF1RYKLBMA',
    appId: '1:307992644408:android:e98e2961536d4ab9384fcd',
    messagingSenderId: '307992644408',
    projectId: 'wett-profis',
    databaseURL: 'https://wett-profis.firebaseio.com',
    storageBucket: 'wett-profis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOE5GOKaEtfSP4nchfTEiqQDHfE2vVzxg',
    appId: '1:307992644408:ios:4e2eae219019a7c2384fcd',
    messagingSenderId: '307992644408',
    projectId: 'wett-profis',
    databaseURL: 'https://wett-profis.firebaseio.com',
    storageBucket: 'wett-profis.firebasestorage.app',
    iosClientId: '307992644408-b6l56r1g27o4s3cuncrkapj7117ns3sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsplit3',
  );
}
